# Generated by Django 4.0.1 on 2022-06-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_detalleventa_cantidad_detalleventa_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_nombre', models.CharField(max_length=10)),
                ('cant_click', models.IntegerField()),
                ('usuario', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(default='En espera', max_length=30),
        ),
    ]
