# Generated by Django 4.0.5 on 2022-06-12 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_lista_alter_detalleventa_precio_alter_venta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='subscriptor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='n_celular',
            field=models.CharField(max_length=10, verbose_name='Numero celular'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(blank=True, db_column='venta_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.cliente'),
        ),
    ]
